import pygame

SCREENWIDTH = 500
SCREENHEIGHT = 500
TILEWIDTH = 32
TILEHEIGHT = 32
SCREENSIZE = [SCREENWIDTH, SCREENHEIGHT]
SCREEN = pygame.display.set_mode(SCREENSIZE)
COLLECTABLES = []
COLLISION = []
